files.extend-exclude = [
  "flake.lock",
  "flake/dev/flake.lock",
  "Cargo.lock",
  "fuzz/Cargo.lock",
  ".git/**",
  "target/**",
]

[default.extend-words]
ANDed = "ANDed"
WRONLY = "WRONLY"
intoto = "intoto"

[default.extend-identifiers]
ANDed = "ANDed"
